[package]
name = "optics"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
thiserror = { workspace = true }
lalrpop-util = { workspace = true }
once_cell = { workspace = true }
itertools = { workspace = true }
logos = { workspace = true }
serde = { workspace = true }
tapi = { workspace = true }
utoipa = { workspace = true }

[build-dependencies]
lalrpop = { workspace = true }
